# Generated by Django 4.1.1 on 2022-10-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_warehouse_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='warehouse',
            field=models.CharField(max_length=50),
        ),
    ]
