# Generated by Django 4.1.1 on 2022-11-18 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_interested_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
    ]
