# Generated by Django 4.1.1 on 2022-11-18 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
